services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto

    environment:
      - TZ=Europe/Madrid

    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

    ports:
      - "1883:1883"

    restart: unless-stopped
