; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html
;
;   pio run -e tx -t upload   -> placa emisora  (DHT11 -> LoRa)
;   pio run -e rx -t upload   -> placa receptora (LoRa -> MQTT)

[env]
platform = espressif32
board = heltec_wifi_lora_32_V2
framework = arduino
monitor_speed = 115200

lib_deps =
    knolleary/PubSubClient @ ^2.8
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.9
    bblanchon/ArduinoJson @ ^6.21.5
    sandeepmistry/LoRa@^0.8.0

[env:tx]
build_src_filter = +<tx/>
build_flags =
    -I include
    -D MODE=1

[env:rx]
build_src_filter = +<rx/>
build_flags =
    -I include
    -D MODE=0